version: "2"
services:

  node:
    image: "node:latest"
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: "npm i ; npm run dev"





